import '../styles/global.css'
import '../styles/nav.css'
import '../styles/footer.css'
import '../styles/hero.css'
import '../styles/process.css'
import '../styles/about.css'
import '../styles/projects.css'
import '../styles/contact.css'
import '../styles/skills.css'
import '../styles/ssd-banner.css'

import './nav.js'
import './hero-parallax.js'
import './marquee.js'
